### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by jschr** [jschr/electron-react-redux-boilerplate#17]
README is currently pretty bare. 

@pronebird any feedback on what should be included? I might take a stab at it later today.

**Comment by pronebird** [comment]
I looked at https://github.com/chentsulin/electron-react-boilerplate and I think we should maintain similar structure. 

There are couple of thing missing in our README which would be awesome to mention since it's important for people that look for boilerplate for their projects:

1. Quick start guide, e.g. clone + `npm i`
2. Libraries used by boilerplate, i.e React, React-Router, Redux, etc..
3. `mocha` is integrated and we should mention that
4. Packaging instructions. `electron-builder.yml` contains config for distribution. (needs link to https://github.com/electron-userland/electron-builder/wiki/Options, there are lots of settings)

**Comment by jschr** [comment]
Makes sense to me, I'll try to draft something up this weekend which I'll ask you to review.

**Comment by jschr** [comment]
@pronebird https://github.com/jschr/electron-react-redux-boilerplate/commit/32212ca36ab624acd79e2a60d2d4bd317da6f3f8

**Comment by jschr** [comment]
Addressed in https://github.com/jschr/electron-react-redux-boilerplate/pull/19
