### ISSUE TITLE
Getting started with boilerplate

### ISSUE THREAD

**Issue by pronebird** [jschr/electron-react-redux-boilerplate#22]
I am thinking of best practice to get started with boilerplate. Currently we suggest to simply clone repository. 

One of my concerns is commit history which is irrelevant for the app that's being built on top of boilerplate. 

My take on that is to squash entire commit history into single initial commit, i.e.:

```sh
git checkout --orphan new-master master
git commit -m "Initial commit"
git branch -M new-master master
```

But I can imagine it may complicate synchronization between repositories when new updates or fixes to boilerplate are available for merge.

**Comment by jschr** [comment]
When I've cloned other boilerplate projects I'll usually do a `rm -rf .git && git init` because I usually don't want the history and I'm about to change the project enough that I don't particularly care about future changes.

I think that's a similar workflow you are describing? 

We could include a script to re-init / squash the repo and include it in the readme.

**Comment by pronebird** [comment]
Same flow. I guess we could include it in README but I don't see the point to have such script in repository since it's pretty trivial.
