### ISSUE TITLE
CSS modules

### ISSUE THREAD

**Issue by pronebird** [jschr/electron-react-redux-boilerplate#23]
Thinking of adding CSS modules support. Need something for CSS. Any preferences or suggestions? I think babel needs some plugin to `require()` CSS.

**Comment by jschr** [comment]
On the fence about this since there's so many popular ways to handle css. Personally I've been using glamor / aphrodite / style-components so the first thing I would do is remove the dependency in favour of one of those. Not that offering one way out of the box is a bad thing, but unfortunately the react community hasn't really landed on a "one way to rule them all". 

This does beg the question as where do we draw the line if we want to keep the project minimal? We've already decided certain libs like Mocha so definitely not against picking a css lib as default either. 

One potential benefit of a css-in-js library versus css modules is that it doesn't require extra webpack / babel config so replacing them is a bit easier.

**Comment by jschr** [comment]
Another option would be to just add css-module support to the webpack config without adding any additional production dependencies. The user can then add any css-in-js lib after (which wouldn't use the loader) or add their favourite pre-processor (less, sass, etc...) if they want.

**Comment by pronebird** [comment]
I am up for CSS without preprocessors because of simplicity. However the thing is, we would have to plug-in webpack or figure out how to make live reload work with cli tools. I've spent about a day fighting `babel-cli` but couldn't find reliable way to recompile JS that required CSS.

**Comment by jschr** [comment]
I'm good with adding whatever lib you want for CSS since it's pretty trivial to change to your preferred after cloning. If there's anybody else out there reading this with an opinion please share!

@pronebird off-topic but I definitely recommend giving css-in-js a chance! Took a bit of getting used to for me at first but now I use it in most projects. I found it really helped promote small, modular components. Plus you get all the benefits of JS like variables, mixins, loops and conditionals without any preprocessors. You can accomplish all of that with preprocessors too so it really is just a matter of preference for the most part!

**Comment by pronebird** [comment]
We basically have no problem if CSS is in JS, since babel knows how to recompile JS, however finding dependency between CSS and JS is not easy and may require changes to babel-cli itself... 

Webpack can solve that, but I postpone its integration because number of tools needed to run hello world app is already overwhelming.

**Comment by dixon13** [comment]
I personally have been researching this all day. I want to import css and JS from node_module without using webpack or gulp. It's annoying to use them wish there was an easier way to do this.  Is this what you guys are trying to accomplish?

**Comment by jschr** [comment]
The discussion here was around wether or not it made sense for this project to have a default opinion for css. Since there are so many popular ways people are doing css right now, we haven't committed to one single solution.

With CSS modules, we would need an additional dependency like webpack. 

For CSS-in-JS, no additional dependencies are needed but is a fairly strong opinion to take as there are a few equally popular libs the community uses. 

I think your use case of simply importing a css file from node modules already works. For example if you `npm install normalize.css`, you'd import it like any other global stylesheet in [index.html](https://github.com/jschr/electron-react-redux-boilerplate/blob/master/app/index.html): 

```html
<link rel="stylsheet" type="text/css" src="../../node_modules/normalize.css/normalize.css">
```

Haven't actually tested this, but I think it should work.

**Comment by jschr** [comment]
Gonna go ahead and close this for now. Let's create a new issue if there's a preferred way of handling CSS.

**Comment by blamh** [comment]
I believe this should be

```html
<link rel="stylesheet" type="text/css" href="../../node_modules/normalize.css/normalize.css">
```

`stylesheet` and `href` instead of `stylsheet` and `src`
