### ISSUE TITLE
Blank page when building app

### ISSUE THREAD

**Issue by uesteibar** [jschr/electron-react-redux-boilerplate#26]
Hi!

Very nice work on this boilerplate :)

I'm getting a blank page when building with `run-s private:clean private:compile private:build:mac`.
It's happening in the following branch https://github.com/uesteibar/sloth-app/tree/integrate-cli

When running `npm start` works fine, but not when building. Already tried everything I could think of but I can't manage to make it work. Could you guys give me a hand on this?

Thank you!

**Comment by jschr** [comment]
hey @uesteibar,

haven't had a chance to reproduce the issue yet but I wonder if it's related to this issue: https://github.com/jschr/electron-react-redux-boilerplate/issues/2?

**Comment by uesteibar** [comment]
@jschr thanks for the quick response :)

I just tried it and I still get the blank page no matter in which folder I am.

**Comment by jschr** [comment]
Here's what I've found:

With electron-react-redux-boilerplate
```bash
git clone git@github.com:jschr/electron-react-redux-boilerplate.git
cd electron-react-redux-boilerplate
npm install
npm run develop #worked
npm run pack:mac 
open dist/mac/MyApp.app #worked
```

With sloth-app
```bash
git clone git@github.com:uesteibar/sloth-app.gitelectron-react-redux-boilerplate
cd sloth-app
git checkout integrate-cli
npm install
npm run start #worked
npm run pack
open dist/mac/Sloth.app #broken :(
```

I then installed https://github.com/sindresorhus/electron-debug to help debug (something we may want to add to this project).

I see this error in the console when running the package:

<img width="802" alt="screen shot 2017-04-07 at 7 18 49 pm" src="https://cloud.githubusercontent.com/assets/1163252/24822904/0c7ea888-1bc7-11e7-8dba-7034a5072115.png">

So looks like it's error because the packaged app is missing some files sepecifically `config/packages/base.json`

Why's that happening? Not sure. [electron-builder.yml](https://github.com/jschr/electron-react-redux-boilerplate/blob/master/electron-builder.yml) specifies to include `build/` so it should grab those files.

To confirm if the files are actually being included I set `asmr: false`. Doing that will let you browse the included files of the package: 

<img width="648" alt="screen shot 2017-04-07 at 7 26 59 pm" src="https://cloud.githubusercontent.com/assets/1163252/24823026/37f0b9c4-1bc8-11e7-8f90-9016bf251a20.png">

Looks like they are there! So maybe it has something to do with the way you are requiring them...

Taking a look at the code here: https://github.com/uesteibar/sloth-app/blob/integrate-cli/app/ducks/packages/index.js#L4

Aha! Notice how in the packaged app contents screenshot it only includes the `build` folder. The way you are requiring them expects the src code to be included.

So the real path when bundled is `./app/build/config/packages/...`.

The fix is to use make sure you are including the full path to the electron app:

```js
import path from 'path';
import { remote } from 'electron';

...

const base = fs.readJsonSync(path.resolve(appPath, './build/config/packages/base.json'));
const developer = fs.readJsonSync(path.resolve(appPath, './build/config/packages/developer.json'));
const designer = fs.readJsonSync(path.resolve(appPath, './build/config/packages/designer.json'));

...

const initialState = {
  packagesForRoles: loadPackages(),
  packages: [],
  common: fs.readJsonSync(path.resolve(appPath, './build/config/packages/common.json'))
};
```

<img width="804" alt="screen shot 2017-04-07 at 7 57 01 pm" src="https://cloud.githubusercontent.com/assets/1163252/24823446/6734712c-1bcc-11e7-9256-813f226e39aa.png">

Success! 

Importing from /build may break your development workflow so you may only want to do that when not in development.

Happy coding!

Jordan

**Comment by uesteibar** [comment]
wow thanks @jschr!!!
Didn't know about `electron-debug`, but I'm definitely having a look into it :)

Closing this issue now, and as said, keep the great work here! 😸

**Comment by pronebird** [comment]
We could technically get rid of build/ and extract straight into app/ in asar.

I usually use relative path using __dirname, I.e from app.js:

```
path.join(__dirname, "config/...");
```
