### ISSUE TITLE
webpack

### ISSUE THREAD

**Issue by alexbigapps23** [jschr/electron-react-redux-boilerplate#42]
hi how i can add webpack for css sass support ?

**Comment by pronebird** [comment]
Hi,

This boilerplate specifically avoids webpack and uses all CLI tools to compile JS directly via `package.json` scripts to make it as easy as possible to get started with modern Javascript without learning the myriads of generators, tools and configurations. 

I believe it wouldn't bee too hard to plug in SASS compiler and file watcher if desired.

However, personally I don't see any need for CSS preprocessors with this boilerplate because Electron is bounded by single browser engine (WebKit) and because React is powerful enough so the styles can be produced dynamically using Javascript.

At the same time if you build something cross platform for example using ReactXP, you're better off without any CSS either and move on with styles in JS.

**Comment by jschr** [comment]
You can use [electron-compile](https://github.com/electron-userland/electron-compile#how-does-it-work-easiest-way) to automatically compile your sass files. 

Let us know if you get this working, might be something we want to consider adding to this boilerplate.

**Comment by jschr** [comment]
Closing, please post back if you find a solution.
