### ISSUE TITLE
Using proxies

### ISSUE THREAD

**Issue by vicesalles** [jschr/electron-react-redux-boilerplate#46]
Hi guys,

I'm trying to port a react app to electron using your awesome boilerplate. I'm getting stuck in the calls to the server. In the react app I'm using a proxy in the package.json for some routes:

```
"proxy": {   
    "/auth/linkedin": {
      "target": "http://localhost:5000"
    },
    "/v1/*": {
      "target": "http://localhost:5000"
    }
  }
```
Then, in my actions, I use the axios package for the callings. In electron, after running the building process those routes turn into absolute paths ignoring the proxy. The question:

**TLDR**: Is it possible to specify a proxy for some routes? 

greetings

**Comment by pronebird** [comment]
Hi,

How do you make calls to your server? Do you use `fetch()`?

Cheers,
Andrej

**Comment by vicesalles** [comment]
Hi Andrej! 

I'm using the [axios ](https://github.com/axios/axios) package which, I think, uses XMLHttpRequest . Should I use the fetch api instead?

greetings,
Vice

**Comment by pronebird** [comment]
That probably shouldn't matter. I must admit I have very little understanding of what you're trying to achieve. Do you experience some CORS issue or what is this about?

**Comment by vicesalles** [comment]
The definitive endpoints direction is not clear yet and I opted for the proxy solution to rapidly adapt my client app to those incomming changes.

**Comment by pronebird** [comment]
OK I think I understand your problem a little bit more now. I'd give a shot to service worker.

1. Register service worker in `app/app.js`

```
// app/app.js
navigator.serviceWorker.register(path.join(__dirname, 'service-worker.js'))
.then((registration) => {
  console.log('ServiceWorker registration successful with scope: ', registration.scope);
}).catch((err) => {
  console.log('ServiceWorker registration failed: ', err);
});
```

2. Then add a service worker implementation somewhere in `app/service-worker.js`:

```
// app/service-worker.js
this.addEventListener('install', function (event) {
  console.log('Installing Service Worker');
  event.waitUntil(this.skipWaiting());
});

this.addEventListener('activate', function (event) {
  event.waitUntil(this.clients.claim());
});

this.addEventListener('fetch', function(event) {
  // remove absolute path from url
  var serviceWorkerDir = location.href.replace(location.pathname);
  var url = event.request.url.replace(serviceWorkerDir, '');
 
  if(url.startsWith('/v1/') || url.startsWith('/auth/linkedin')) {
    // clone request changing URL
    // Probably should work this way https://fetch.spec.whatwg.org/#requestinfo
    var newRequest = new Request(event.request, { 
      url: 'http://localhost:5000/' + url
     });
     event.respondWith(fetch(newRequest));
  }
});
```

3. You need to make sure babel does not compile service-worker, so add `--ignore app/service-worker.js` to compilation step (see https://github.com/jschr/electron-react-redux-boilerplate/blob/master/package.json#L62)

```
"private:compile": "babel app/ --ignore app/service-worker.js --copy-files --out-dir build"
```

I haven't tested any of this so you'll probably need to fix a few things here and there. I used service-worker once to cache mapbox tiles without any issues.

**Comment by jschr** [comment]
It sounds like @vicesalles is trying to use the proxy config from create-react-app in this boilerplate:
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#configuring-the-proxy-manually

Since this boilerplate wasn't created with CRA we don't have this functionality out of the box. 

CRA's proxy config is just passed along to `webpack-dev-server`: 
https://webpack.js.org/configuration/dev-server/#devserver-proxy

Unfortunately we are not using webpack either so this isn't easily portable from your existing react app.

> In electron, after running the building process those routes turn into absolute paths ignoring the proxy.

Could you provide a code snippet of your fetch calls or even better -- a repro showing this issue? This boilerplate doesn't currently include any fetch-related logic AFAIK.

@pronebird's solution of using a service worker should work great. It sounds like you are only using this for local dev so if you implement a SW make sure you only register in development. 

It sounds like you just want development to hit the local version of your API rather production. If that's the case your best bet might just be to create an axios instance with the correct baseUrl based on environment:
https://github.com/axios/axios#creating-an-instance

This might look something like this:
```js
// api.js
import axios from 'axios'

const config = {
  development: {
    baseURL: 'http://localhost:5000'
  },
  production: {
    baseURL: 'http://api.server.com'
  }
}

return axios.instance(config[process.env.NODE_ENV]);

// someOtherFile.js
import api from './api'

const response = await api.get('/v1/...')
```

> Is it possible to specify a proxy for some routes?

Axios instances will use the baseURL for all requests using that instance. For local development I've never needed to redirect only some requests to my api to localhost. I'm curious about your use case, can you elaborate more there or provide the full proxy config of your app?

**Comment by jschr** [comment]
@vicesalles Did you get this working?

**Comment by vicesalles** [comment]
Hi @jschr! I Using an axios instance instead of importing and using the library directly did the think. Thank you
